### ISSUE TITLE
密码过期

### ISSUE THREAD

**Issue by lichengzhe** [CloudWise-OpenSource/SAPNetworkMonitor#11]
Your password has expired. To log in you must change it using a client that supports expired passwords.
mysql里面的表user里的字段password_expired要改成N 
多谢鼠标手反馈

**Comment by binque** [comment]
这个是MySQL的使用问题 。

MySQL Password Expiration and Sandbox Mode的问题对应MySQL的不同版本解决方法并不相同，详情请参考MySQL的官方使用手册。
这个问题的链接说明:https://dev.mysql.com/doc/refman/5.7/en/password-expiration-sandbox-mode.html

MySQL的安装问题不作为SAP系统的BUG.
